# Generated by Django 3.1.5 on 2021-02-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_attendee_coffee_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event_room',
        ),
        migrations.AddField(
            model_name='attendee',
            name='event_room_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room1_assigneds', to='manager.event_room'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='event_room_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room2_assigneds', to='manager.event_room'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='coffee_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_assigneds', to='manager.coffee_space'),
        ),
    ]
